// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Inserts a new comment into the comments table
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	// Inserts a new post into the posts table
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	// Inserts a new user into the users table
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Deletes a specific comment from the comments table by ID
	DeleteComment(ctx context.Context, id uuid.UUID) error
	// Deletes a specific post from the posts table by ID
	DeletePost(ctx context.Context, id uuid.UUID) error
	// Retrieves all comments for a specific post from the comments table
	GetAllCommentsForPost(ctx context.Context, postID uuid.UUID) ([]Comment, error)
	// Retrieves all posts from the posts table
	GetAllPosts(ctx context.Context) ([]Post, error)
	// Retrieves a specific post from the posts table by ID
	GetPostByID(ctx context.Context, id uuid.UUID) (Post, error)
	// Retrieves user by email (used for login)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Updates a specific comment in the comments table by ID
	UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error)
	// Updates a specific post in the posts table by ID
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
}

var _ Querier = (*Queries)(nil)
